version: '3.4'
services:

  mariadb:
    image: mariadb:10.2
    container_name: tracker_mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./src/main/resources/sql/:/docker-entrypoint-initdb.d/